:state: closed
:module: lino

#99 [closed] : How can ``dd.apps`` differ from ``settings.SITE.plugins``?
=========================================================================

Here is a problem on which I got stuck today (:blogref:`20140226`).

To reproduce this problem, go to your Lino repository and get today's
version of Lino (`4677bb8e1a
<https://gitlab.com/lino-framework/lino/commit/4677bb8e1ad195355bfb11aa6cf6beeec87833c5>`_)::

    $ cd ~/repositories
    $ git pull

Then run the test suite of :mod:`lino_book.projects.min1`::

    $ cd lino/projects/min1
    $ python manage.py test lino.tests.QuickTest
    
The result is::
    
    FAIL: test01 (lino.tests.lino_tests.QuickTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/luc/hgwork/lino/lino/tests/lino_tests.py", line 35, in test01
        self.assertEqual(settings.SITE.plugins.lino, dd.apps.lino)
    AssertionError: <djangosite.djangosite_site.Plugin object at 0xa53698c> != <djangosite.djangosite_site.Plugin object at 0x8ded4ac>

This seems to indicate that the 
:class:`Plugin <djangosite.djangosite_site.Plugin>` instance which represents the `lino` plugin got instantiated a second time.
I don't understand how this is possible.
    
In :mod:`lino.dd`, Lino creates a shortcut ``dd.apps`` 
which points to ``settings.SITE.plugins``::

  apps = settings.SITE.plugins

Question: How is this possible? Why does this test fail?

Answer: this problem was specific to Lino. 
Details see :blogref:`20140227`.

